spring.application.name=first_springboot_webapp
spring.datasource.url=jdbc:mysql://localhost:3306/student_crud_db
spring.datasource.username=root
spring.datasource.password=WelcomeSql@123
spring.jpa.hibernate.ddl-auto=update